### ISSUE TITLE
Sluggish editor

### ISSUE THREAD

**Issue by redactedscribe** [ZackaryW/obsidian-image-inline#3]
Nice idea, and thank you for the plugin, however even with a small image as base64, the editor becomes slow to respond. Another issue that there's now massive walls of text in the Source view which I primarily work in. If it were possible to collapse these strings in some way, for example to only render them in full when the cursor is within the link, that could help. Both of these issues mean I cannot use your plugin yet, despite the idea being great.

Thanks.

**Comment by ZackaryW** [comment]
Hi there, im very curious about where the slowness comes from since I couldn't replicate this problem on all my working devices (including phone)

second, it is possible to prevent the expansion of links through the use of codeblocks, but unfortunately, that would also mean incompatibility with any other markdown app. I am going to wait till a sizable demand before working on this since that implementation could be a standalone extension all by itself. 

in case anyone had any ideas on how to prevent link expansions, please let me know

**Comment by redactedscribe** [comment]
> Hi there, im very curious about where the slowness comes from since I couldn't replicate this problem on all my working devices (including phone)

It must be something to do with my Obsidian then. If I figure out what, I'll let you know.

> second, it is possible to prevent the expansion of links through the use of codeblocks, but unfortunately, that would also mean incompatibility with any other markdown app.

I'm generally in favour of this too, but how do you mean that codeblocks incompatible with other markdown editors? My general approach to using Obsidian is to only use Obsidian specific things if they'll be easy enough to search and replace at a later date into some more standard flavour. I'd probably be fine with what you have in mind I think...

**Comment by ZackaryW** [comment]
to clarify on my second point, 
Of course, I could turn links into codeblocks to prevent expansion, which is the straightforward method.
But that also means when you open the notes in any other app, you can only see garbage. Current implementation ensures the inline images will always be visible and I deem that as a core feature.
Unfortunately, I am not aware of any implementation that can overwrite link behavior handling (since Im still new to both js and obsidian api)
